name = "GIFTI"
uuid = "0e488d3e-ad97-4b95-b07b-1587880fd035"
authors = ["Michael Myers"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
